// Banc de preguntes per als exàmens entre escenaris (estil test teòric del permís B, sense imatges).
// La PRIMERA opció de cada pregunta és la correcta (es barregen en mostrar-les).
// Per a afegir-ne més, n'hi ha prou amb afegir objectes { q, o } a qualsevol secció.
const QUESTIONS = [
  // ---------- VELOCITAT ----------
  { q: "Quina és la velocitat màxima genèrica per a un turisme en autopista i autovia?",
    o: ["120 km/h", "100 km/h", "130 km/h", "110 km/h"] },
  { q: "En una via urbana amb un únic carril per sentit de circulació, quina és la velocitat màxima genèrica?",
    o: ["30 km/h", "20 km/h", "50 km/h", "40 km/h"] },
  { q: "En una via urbana amb dos o més carrils per sentit de circulació, quina és la velocitat màxima genèrica?",
    o: ["50 km/h", "30 km/h", "60 km/h", "40 km/h"] },
  { q: "En una via urbana de plataforma única de calçada i vorera, quina és la velocitat màxima genèrica?",
    o: ["20 km/h", "30 km/h", "10 km/h", "40 km/h"] },
  { q: "Quina és la velocitat màxima genèrica per a un turisme en una carretera convencional?",
    o: ["90 km/h", "100 km/h", "80 km/h", "70 km/h"] },
  { q: "Llevat de senyalització, per davall de quina velocitat no pot circular un turisme per autopista?",
    o: ["60 km/h", "50 km/h", "80 km/h", "No hi ha velocitat mínima"] },
  { q: "En una carretera convencional, per davall de quina velocitat no pot circular un turisme, llevat de causa justificada?",
    o: ["45 km/h", "30 km/h", "60 km/h", "No hi ha velocitat mínima"] },
  { q: "Quina és la velocitat màxima d'un autobús en autopista?",
    o: ["100 km/h", "90 km/h", "120 km/h", "80 km/h"] },
  { q: "Quina és la velocitat màxima d'un turisme amb remolc en autopista?",
    o: ["90 km/h", "80 km/h", "100 km/h", "120 km/h"] },
  { q: "Quina és la velocitat màxima a què pot circular un ciclomotor?",
    o: ["45 km/h", "50 km/h", "40 km/h", "60 km/h"] },
  { q: "En avançar en una carretera convencional, pot superar el límit de velocitat?",
    o: ["No, en cap cas", "Sí, fins a 20 km/h més", "Sí, fins a 10 km/h més",
        "Només si l'avançament dura menys de 15 segons"] },
  { q: "En augmentar la velocitat, què li passa al camp visual del conductor?",
    o: ["Es redueix", "S'amplia", "No varia", "Només varia de nit"] },
  { q: "Si es duplica la velocitat, la distància de frenada...",
    o: ["Es multiplica aproximadament per quatre", "Es duplica", "No varia", "Es redueix a la meitat"] },

  // ---------- DISTÀNCIES I FRENADA ----------
  { q: "Quina distància de seguretat ha de mantindre amb el vehicle de davant?",
    o: ["La suficient per a poder detindre's sense col·lidir en cas de frenada brusca", "Sempre 10 metres",
        "Sempre 50 metres", "Només cal mantindre-la en autopista"] },
  { q: "La distància de detenció d'un vehicle és la suma de...",
    o: ["La distància de reacció i la distància de frenada", "La distància de frenada i la de seguretat",
        "La distància de reacció i la de seguretat", "Només la distància de frenada"] },
  { q: "Amb el paviment mullat, la distància de frenada...",
    o: ["Augmenta", "Disminueix", "No varia", "Només varia si els pneumàtics són nous"] },
  { q: "Quin d'aquests factors augmenta el temps de reacció del conductor?",
    o: ["El cansament", "Portar els pneumàtics nous", "Circular de dia", "Portar el cinturó posat"] },
  { q: "En un túnel, quina distància mínima ha de mantindre un turisme amb el vehicle que el precedeix?",
    o: ["100 metres o 4 segons", "50 metres o 2 segons", "150 metres o 6 segons", "25 metres"] },
  { q: "En una frenada d'emergència amb un vehicle sense ABS, si es bloquegen les rodes, què ha de fer?",
    o: ["Deixar anar el fre i tornar a frenar", "Mantindre el fre a fons", "Girar el volant bruscament",
        "Posar el punt mort i esperar"] },
  { q: "Quin avantatge principal té el sistema ABS?",
    o: ["Permet mantindre el control de la direcció durant una frenada forta", "Redueix sempre la distància de frenada a la meitat",
        "Evita haver de mantindre la distància de seguretat", "Impedeix l'aquaplaning"] },

  // ---------- AVANÇAMENTS ----------
  { q: "Quina separació lateral mínima ha de deixar en avançar un ciclista fora de poblat?",
    o: ["1,5 metres", "1 metre", "0,5 metres", "2,5 metres"] },
  { q: "Fora de poblat, quina separació lateral mínima ha de deixar en avançar un vianant o un animal?",
    o: ["1,5 metres", "0,5 metres", "1 metre", "3 metres"] },
  { q: "Quan està permés avançar per la dreta?",
    o: ["Quan el vehicle de davant ha indicat clarament que gira a l'esquerra", "Mai",
        "Sempre que el carril dret estiga lliure", "Quan el vehicle de davant va lent"] },
  { q: "On està prohibit avançar?",
    o: ["En revolts i canvis de rasant de visibilitat reduïda", "En qualsevol recta",
        "En autopistes amb tres carrils", "Sempre que hi haja línia discontínua"] },
  { q: "Quan un altre vehicle l'avança, què ha de fer vosté?",
    o: ["No augmentar la velocitat i facilitar l'avançament", "Accelerar per a no quedar-se arrere",
        "Frenar bruscament", "Circular pel centre de la calçada"] },
  { q: "Està permés avançar en un pas a nivell?",
    o: ["No", "Sí, si no s'acosta cap tren", "Sí, si hi ha barreres", "Només a vehicles de dues rodes"] },
  { q: "Es pot avançar en un túnel on només hi ha un carril per al seu sentit de circulació?",
    o: ["No", "Sí, si hi ha bona visibilitat", "Sí, si el túnel és curt", "Només de dia"] },

  // ---------- POSICIÓ EN LA VIA ----------
  { q: "En una autopista amb tres carrils per sentit, per quin carril ha de circular normalment un turisme?",
    o: ["Pel de la dreta, i pot utilitzar els altres quan les circumstàncies ho aconsellen", "Pel central",
        "Pel de l'esquerra", "Per qualsevol, indistintament"] },
  { q: "En poblat, en una calçada amb almenys dos carrils per sentit delimitats per marques, per quin carril pot circular un turisme?",
    o: ["Pel que més convinga a la seua destinació", "Sempre pel de la dreta",
        "Sempre pel de l'esquerra", "Pel central obligatòriament"] },
  { q: "Per on han de circular les bicicletes en una carretera convencional que té voral transitable?",
    o: ["Per la voral de la dreta", "Pel centre del carril", "Per la voral de l'esquerra", "Per on vulguen"] },
  { q: "Poden circular els ciclistes en grup en una carretera?",
    o: ["Sí, en columna de dos com a màxim", "No, sempre en fila d'un", "Sí, en columna de tres", "Sí, sense limitació"] },
  { q: "Pot un turisme circular per la voral d'una autopista?",
    o: ["No, només en cas d'emergència", "Sí, si va lent", "Sí, per a avançar", "Sí, si hi ha retencions"] },
  { q: "Per on han de circular els vianants fora de poblat quan no hi ha vorera ni zona per a vianants?",
    o: ["Per l'esquerra", "Per la dreta", "Pel centre de la calçada", "Per on vulguen"] },
  { q: "De nit i fora de poblat, un vianant que circula per la calçada o la voral ha de portar...",
    o: ["Un element lluminós o reflectant", "Roba de color fosc", "Res en especial", "Un casc"] },

  // ---------- PRIORITAT DE PAS ----------
  { q: "En una intersecció sense senyalitzar, a qui ha de cedir el pas?",
    o: ["Als vehicles que s'aproximen per la seua dreta", "Als que s'aproximen per l'esquerra",
        "Al vehicle de major grandària", "A ningú; passa primer qui arriba abans"] },
  { q: "En una intersecció sense senyalitzar entre una via pavimentada i una sense pavimentar, qui té preferència?",
    o: ["El vehicle que circula per la via pavimentada", "El que circula per la via sense pavimentar",
        "El que ve per la dreta, sempre", "El vehicle més gran"] },
  { q: "En una intersecció sense senyalitzar, qui té preferència respecte als vehicles de carretera?",
    o: ["Els vehicles que circulen sobre rails, com el tramvia", "Els autobusos", "Els turismes", "Les motocicletes"] },
  { q: "En una rotonda, llevat de senyalització, qui té preferència?",
    o: ["Els vehicles que ja circulen per la rotonda", "Els que hi accedeixen",
        "Els que venen per la dreta per a entrar", "El vehicle de major grandària"] },
  { q: "En un tram estret de molt de pendent sense senyalitzar, qui té preferència de pas?",
    o: ["El vehicle que puja, llevat que el que baixa arribe abans a un apartador", "El vehicle que baixa",
        "El vehicle més gran", "El que arribe primer al tram"] },
  { q: "Quan gira per a entrar en una altra via, què ha de fer si hi ha vianants creuant-la, encara que no hi haja pas per a vianants?",
    o: ["Cedir-los el pas", "Continuar, perquè té preferència", "Tocar el clàxon", "Accelerar per a passar abans"] },
  { q: "Què ha de fer si s'acosta un vehicle prioritari amb els senyals lluminosos i acústics en funcionament?",
    o: ["Facilitar-li el pas, apartant-se normalment a la dreta", "Continuar igual",
        "Frenar en sec on estiga", "Accelerar per a no molestar"] },
  { q: "En incorporar-se a una autovia des d'un carril d'acceleració, qui té preferència?",
    o: ["Els vehicles que ja circulen per l'autovia", "El vehicle que s'incorpora",
        "El vehicle més ràpid", "Qui arribe primer"] },
  { q: "Un grup de ciclistes creua una intersecció i el primer ja hi ha entrat. Qui té preferència?",
    o: ["El grup de ciclistes, que es considera una única unitat", "El turisme que arriba",
        "Només el primer ciclista", "Qui vinga per la dreta"] },

  // ---------- SENYALS I MARQUES ----------
  { q: "Quines indicacions prevalen sobre totes les altres?",
    o: ["Les dels agents de circulació", "Els semàfors", "Els senyals verticals", "Les marques viàries"] },
  { q: "Un semàfor està en roig, però un agent li indica que passe. Què ha de fer?",
    o: ["Passar, obeint l'agent", "Detindre's pel semàfor", "Tocar el clàxon i esperar", "Fer marxa arrere"] },
  { q: "Davant d'una llum groga fixa en un semàfor, què ha de fer?",
    o: ["Detindre's, llevat que no puga fer-ho en condicions de seguretat", "Accelerar per a passar abans del roig",
        "Passar sempre amb precaució", "Detindre's només si hi ha vianants"] },
  { q: "Què indica una llum groga intermitent en un semàfor?",
    o: ["Que ha d'extremar la precaució i, si cal, cedir el pas", "Prohibició de passar",
        "Que el semàfor està avariat i té preferència", "Que ha d'accelerar"] },
  { q: "Què indica una llum roja intermitent en un pas a nivell?",
    o: ["Prohibició de passar", "Que pot passar amb precaució", "Que el tren ja ha passat", "Res, és informativa"] },
  { q: "Què significa el senyal de STOP?",
    o: ["Detenció obligatòria i cedir el pas", "Només cedir el pas si ve algú",
        "Reduir la velocitat", "Prohibit estacionar"] },
  { q: "Pot creuar una línia longitudinal contínua?",
    o: ["No, ni creuar-la ni circular-hi per damunt", "Sí, per a avançar",
        "Sí, si no ve ningú", "Només de dia"] },
  { q: "Una línia contínua adossada a una discontínua: quan la pot creuar?",
    o: ["Quan la discontínua està al costat del seu carril", "Quan la contínua està al costat del seu carril",
        "Mai", "Sempre"] },
  { q: "Què indica una línia groga contínua al costat de la vorada?",
    o: ["Prohibició de parar i d'estacionar", "Només prohibició d'estacionar",
        "Zona de càrrega i descàrrega", "Estacionament de pagament"] },
  { q: "Què indica una línia groga discontínua al costat de la vorada?",
    o: ["Prohibició d'estacionar", "Prohibició de parar i d'estacionar",
        "Estacionament permés", "Carril bici"] },
  { q: "Què indica una marca groga en zig-zag?",
    o: ["Prohibició d'estacionar en eixe lloc", "Zona de vianants", "Carril reservat per a bicicletes", "Reductor de velocitat"] },

  // ---------- LLUMS ----------
  { q: "Quan ha de substituir la llum de carretera (llarga) per la d'encreuament?",
    o: ["Quan es creue amb altres vehicles o puga enlluernar algú", "Només en poblat",
        "Només quan plou", "Mai de nit"] },
  { q: "Si un altre vehicle l'enlluerna de nit, què ha de fer?",
    o: ["Reduir la velocitat i mirar cap a la vora dreta de la calçada", "Encendre la llum de carretera",
        "Tancar els ulls un moment", "Frenar en sec"] },
  { q: "Les motocicletes han de circular amb la llum d'encreuament encesa...",
    o: ["També de dia", "Només de nit", "Només dins de túnels", "Només quan plou"] },
  { q: "Quan està permés encendre el llum antiboira posterior?",
    o: ["Només en condicions especialment desfavorables, com ara boira espessa o pluja molt intensa",
        "Sempre que siga de nit", "En qualsevol via interurbana sense il·luminar", "Quan plou, encara que siga poc"] },
  { q: "Quin enllumenat ha de portar encés, com a mínim, en circular per un túnel?",
    o: ["La llum d'encreuament", "Cap, si el túnel està il·luminat", "Només la llum de posició", "Els llums antiboira davanters"] },
  { q: "Per a què es poden utilitzar els llums d'emergència amb el vehicle en marxa?",
    o: ["Per a advertir d'una reducció brusca de velocitat o d'una detenció imprevista", "Per a avançar",
        "Per a estacionar en doble fila", "Per a circular per la voral"] },

  // ---------- PARADA I ESTACIONAMENT ----------
  { q: "Quina diferència hi ha entre parada i estacionament?",
    o: ["La parada no supera els 2 minuts i el conductor no abandona el vehicle",
        "La parada pot durar fins a 10 minuts", "No hi ha cap diferència", "L'estacionament no supera els 2 minuts"] },
  { q: "On està prohibit parar?",
    o: ["En revolts i canvis de rasant de visibilitat reduïda, passos a nivell i túnels", "En qualsevol carrer de poblat",
        "En totes les vies interurbanes", "Al costat d'una vorada blanca"] },
  { q: "En una via interurbana, on s'ha de parar o estacionar?",
    o: ["Fora de la calçada, al costat dret, deixant lliure la part transitable de la voral", "En la calçada, al costat esquerre",
        "Al mig del carril, amb els llums d'emergència", "On es vulga"] },
  { q: "Està permés estacionar en doble fila?",
    o: ["No", "Sí, durant 5 minuts", "Sí, amb els llums d'emergència", "Sí, si el conductor queda dins"] },
  { q: "Si estaciona en una pujada amb vorada, cap a on ha de deixar girades les rodes davanteres?",
    o: ["Cap al costat contrari a la vorada", "Cap a la vorada", "Rectes", "És indiferent"] },

  // ---------- MANIOBRES ----------
  { q: "Quina distància màxima es pot recórrer marxa arrere?",
    o: ["15 metres, sense envair un encreuament de vies", "25 metres", "50 metres", "No hi ha límit si es fa amb precaució"] },
  { q: "Està permesa la marxa arrere en una autopista?",
    o: ["No", "Sí, si t'has passat l'eixida", "Sí, per la voral", "Sí, de nit"] },
  { q: "Està permés el canvi de sentit en una autopista?",
    o: ["No, només pels llocs habilitats a aquest efecte", "Sí, si no ve ningú",
        "Sí, per la mitjana", "Sí, de nit"] },
  { q: "Per a girar a l'esquerra en una via de doble sentit, com s'ha de col·locar?",
    o: ["Com més a prop possible de l'eix central de la calçada", "Com més a la dreta possible",
        "Al mig del carril contrari", "És indiferent"] },
  { q: "Cal senyalitzar un gir encara que no hi haja cap altre vehicle?",
    o: ["Sí, sempre", "No, només si hi ha vehicles", "Només de nit", "Només en poblat"] },
  { q: "Com s'ha d'utilitzar el carril de desacceleració en eixir d'una autovia?",
    o: ["Entrar-hi amb antelació i reduir la velocitat dins del carril", "Frenar abans d'entrar-hi, en el carril principal",
        "Entrar-hi a l'últim moment", "No cal fer-lo servir"] },
  { q: "En un carril d'acceleració, què ha de fer?",
    o: ["Adequar la velocitat a la dels vehicles que circulen pel carril principal", "Detindre's al final sempre",
        "Circular a velocitat reduïda", "Entrar sense mirar, perquè té preferència"] },

  // ---------- AUTOPISTES, TÚNELS I PASSOS A NIVELL ----------
  { q: "Què ha de fer si queda detingut dins d'un túnel per una retenció llarga?",
    o: ["Apagar el motor", "Tocar el clàxon", "Fer marxa arrere", "Eixir del vehicle i caminar pel carril"] },
  { q: "Davant d'un pas a nivell sense barreres, què ha de fer?",
    o: ["Extremar la precaució i assegurar-se que no s'acosta cap tren abans de creuar", "Creuar ràpidament",
        "Tocar el clàxon i passar", "Parar-se damunt de les vies per a mirar"] },
  { q: "Està permés canviar de sentit dins d'un túnel?",
    o: ["No", "Sí, si el túnel és llarg", "Sí, si hi ha poc trànsit", "Només amb autorització del conductor de darrere"] },

  // ---------- METEOROLOGIA ----------
  { q: "Si el seu vehicle entra en aquaplaning, què ha de fer?",
    o: ["Subjectar fermament el volant i alçar el peu de l'accelerador sense frenar bruscament",
        "Frenar a fons", "Accelerar per a recuperar adherència", "Girar bruscament el volant"] },
  { q: "Amb vent lateral fort, què ha de fer?",
    o: ["Subjectar fermament el volant i reduir la velocitat", "Augmentar la velocitat",
        "Circular pel centre de la calçada", "Encendre la llum antiboira"] },
  { q: "On és més probable trobar plaques de gel a l'hivern?",
    o: ["En zones d'ombra i en ponts", "En zones assolellades", "En rectes llargues", "En poblat"] },
  { q: "En quines rodes s'han de col·locar les cadenes per a neu?",
    o: ["En les rodes motrius", "Sempre en les davanteres", "Sempre en les posteriors", "En la de recanvi"] },
  { q: "Per què el ferm és especialment lliscant en els primers minuts de pluja?",
    o: ["Perquè l'aigua es mescla amb la pols i l'oli acumulats", "Perquè l'aigua està més freda",
        "Perquè els pneumàtics es desinflen", "No és més lliscant"] },
  { q: "Amb boira, què és recomanable?",
    o: ["Reduir la velocitat i augmentar la distància de seguretat", "Circular amb la llum de carretera",
        "Seguir de prop el vehicle de davant", "Circular per l'esquerra"] },

  // ---------- SEGURETAT PASSIVA ----------
  { q: "A partir de quina estatura pot un menor utilitzar el cinturó de seguretat en lloc d'un sistema de retenció infantil?",
    o: ["Més de 135 cm", "Més de 120 cm", "Més de 150 cm", "Més de 140 cm"] },
  { q: "És obligatori el cinturó de seguretat en els seients posteriors?",
    o: ["Sí", "No", "Només en autopista", "Només per als menors"] },
  { q: "Han de portar el cinturó de seguretat les dones embarassades?",
    o: ["Sí, amb la banda inferior per davall del ventre", "No, estan exemptes",
        "Només en vies interurbanes", "Només si ho diu el metge"] },
  { q: "Si col·loca una cadira infantil orientada cap arrere en el seient del copilot, què ha de fer?",
    o: ["Desactivar l'airbag frontal del copilot", "Res especial", "Portar la cadira sense ancoratge", "Posar el seient totalment inclinat"] },
  { q: "A quina altura s'ha de regular el reposacaps?",
    o: ["Amb la part superior a l'altura de la part superior del cap", "A l'altura del coll",
        "A l'altura de les espatles", "Com més baix, millor"] },
  { q: "És obligatori el casc per als passatgers de motocicletes i ciclomotors?",
    o: ["Sí", "No", "Només en vies interurbanes", "Només si són menors"] },
  { q: "En bicicleta per una via urbana, per a qui és obligatori el casc?",
    o: ["Per als menors de 16 anys", "Per a tots", "Per a ningú", "Només per als majors de 65 anys"] },
  { q: "Quina és l'edat mínima general per a viatjar com a passatger en una motocicleta?",
    o: ["12 anys", "7 anys", "16 anys", "10 anys"] },

  // ---------- VEHICLE I MANTENIMENT ----------
  { q: "Quina és la profunditat mínima legal del dibuix dels pneumàtics d'un turisme?",
    o: ["1,6 mm", "1 mm", "2,5 mm", "3 mm"] },
  { q: "Quan s'ha de comprovar la pressió dels pneumàtics?",
    o: ["En fred", "Després d'un viatge llarg", "En calent, en qualsevol moment", "Només a l'estiu"] },
  { q: "Si s'encén el testimoni de pressió d'oli durant la marxa, què ha de fer?",
    o: ["Detindre's i apagar el motor com més prompte millor", "Continuar fins a casa",
        "Accelerar", "Res, és normal"] },
  { q: "Quan ha de passar la primera ITV un turisme d'ús particular?",
    o: ["Als 4 anys de la seua matriculació", "Als 2 anys", "Als 5 anys", "A l'any"] },
  { q: "Està permés baixar un pendent en punt mort?",
    o: ["No", "Sí, per a estalviar combustible", "Sí, si el pendent és suau", "Només en poblat"] },
  { q: "En un descens llarg, com ha d'ajudar els frens?",
    o: ["Utilitzant el fre motor amb una marxa curta", "Posant el punt mort",
        "Apagant el motor", "Frenant de manera contínua"] },
  { q: "Està permés remolcar un vehicle avariat amb el seu turisme?",
    o: ["No, només ho poden fer vehicles destinats a eixe fi, com les grues", "Sí, amb una corda",
        "Sí, si la distància és curta", "Sí, de dia"] },

  // ---------- CONDUCCIÓ EFICIENT ----------
  { q: "Per a una conducció eficient, com s'ha d'utilitzar el canvi de marxes?",
    o: ["Canviant a marxes llargues com més prompte millor, a poques revolucions", "Esgotant cada marxa al màxim",
        "Circulant sempre en segona", "Utilitzant el punt mort tant com es puga"] },
  { q: "En una detenció de més d'un minut, què és recomanable per a estalviar combustible?",
    o: ["Apagar el motor", "Deixar el motor en marxa", "Accelerar de tant en tant", "Encendre l'aire condicionat"] },
  { q: "Quin estil de conducció és més eficient?",
    o: ["Mantindre una velocitat uniforme i anticipar-se", "Accelerar i frenar sovint",
        "Circular sempre a la velocitat màxima", "Circular en marxes curtes"] },

  // ---------- FACTORS DE RISC ----------
  { q: "Quina és l'única manera d'eliminar l'alcohol de l'organisme?",
    o: ["Deixar passar el temps", "Prendre un cafè", "Dutxar-se amb aigua freda", "Menjar molt"] },
  { q: "Està obligat a sotmetre's a les proves d'alcoholèmia?",
    o: ["Sí, qualsevol conductor quan ho requerisca un agent", "Només si ha tingut un accident",
        "Només si ha comés una infracció", "No, és voluntari"] },
  { q: "Negar-se a fer les proves d'alcohol o drogues quan ho requereix un agent és...",
    o: ["Un delicte", "Una infracció lleu", "Una infracció sense conseqüències", "Un dret del conductor"] },
  { q: "Està permés conduir amb presència de drogues en l'organisme?",
    o: ["No", "Sí, si no afecten la conducció", "Sí, en trajectes curts", "Sí, si són en poca quantitat"] },
  { q: "Cada quant de temps es recomana descansar en un viatge llarg?",
    o: ["Cada 2 hores o 200 km, aproximadament", "Cada 6 hores", "Només quan s'arriba", "Cada 30 minuts"] },
  { q: "Si nota somnolència mentre condueix, què ha de fer?",
    o: ["Detindre's en un lloc segur i descansar", "Obrir la finestra i continuar",
        "Pujar el volum de la música", "Accelerar per a arribar abans"] },
  { q: "Els medicaments amb el pictograma d'un cotxe dins d'un triangle...",
    o: ["Poden afectar la capacitat per a conduir", "Milloren els reflexos",
        "No tenen cap efecte en la conducció", "Només afecten els conductors professionals"] },
  { q: "Pot conduir amb auriculars connectats a un reproductor de so?",
    o: ["No", "Sí, a volum baix", "Sí, només en una orella", "Sí, en autopista"] },
  { q: "Quants punts es perden per conduir utilitzant el telèfon mòbil subjecte amb la mà?",
    o: ["6 punts", "3 punts", "4 punts", "2 punts"] },
  { q: "Quants punts es perden per no utilitzar el cinturó de seguretat?",
    o: ["4 punts", "3 punts", "2 punts", "6 punts"] },

  // ---------- ACCIDENTS I PRIMERS AUXILIS ----------
  { q: "Què signifiquen les sigles PAS davant d'un accident?",
    o: ["Protegir, Avisar i Socórrer", "Parar, Ajudar i Sortir", "Prevenir, Actuar i Salvar", "Parar, Avisar i Seguir"] },
  { q: "A quin número de telèfon s'ha de trucar en cas d'emergència?",
    o: ["112", "091", "061", "010"] },
  { q: "En un accident, s'ha de llevar el casc a un motorista ferit?",
    o: ["No, llevat de casos imprescindibles com que no puga respirar", "Sí, sempre",
        "Sí, perquè respire millor", "Sí, per a veure si té ferides"] },
  { q: "Quan es pot moure un ferit d'un accident?",
    o: ["Només si hi ha un perill imminent, com un incendi", "Sempre, per a posar-lo còmode",
        "Sempre, per a portar-lo a l'hospital", "Mai, en cap cas"] },
  { q: "Davant d'una hemorràgia externa, què s'ha de fer primer?",
    o: ["Comprimir la ferida", "Donar-li aigua", "Alçar-li el cap", "Llevar-li la roba"] },
  { q: "Si ha de baixar del vehicle en una via interurbana per una avaria, què ha de fer?",
    o: ["Posar-se l'armilla reflectant abans d'eixir", "Eixir ràpidament sense res",
        "Quedar-se al mig de la calçada", "Posar-se l'armilla quan ja estiga fora"] },
  { q: "Quin dispositiu de senyalització prèvia de perill és obligatori en els turismes des de l'1 de gener de 2026?",
    o: ["La balisa lluminosa V-16 connectada", "Dos triangles d'emergència",
        "Un triangle i una armilla reflectant", "Només els llums d'emergència del vehicle"] },
  { q: "On s'ha de col·locar la balisa V-16?",
    o: ["En la part més alta del vehicle, com ara el sostre", "A 50 metres darrere del vehicle",
        "Dins del maleter", "Davall del vehicle"] },

  // ---------- PERMÍS, PUNTS I DOCUMENTACIÓ ----------
  { q: "Amb quants punts comença un conductor que obté el seu primer permís de conducció?",
    o: ["8 punts", "12 punts", "6 punts", "15 punts"] },
  { q: "Durant quant de temps ha de portar el senyal «L» un conductor novell?",
    o: ["1 any", "6 mesos", "2 anys", "3 anys"] },
  { q: "Si ha perdut alguns punts, quant de temps ha de passar sense cometre infraccions per a recuperar el saldo inicial?",
    o: ["2 anys", "6 mesos", "5 anys", "10 anys"] },
  { q: "Quants punts es poden recuperar amb un curs de recuperació parcial?",
    o: ["Fins a 6 punts", "Tots", "Fins a 2 punts", "Fins a 12 punts"] },
  { q: "Si es perden tots els punts, quant de temps ha de passar per a tornar a obtindre el permís (conductor no professional)?",
    o: ["6 mesos", "1 mes", "5 anys", "No es pot tornar a obtindre"] },
  { q: "Cada quant de temps s'ha de renovar el permís B un conductor menor de 65 anys?",
    o: ["Cada 10 anys", "Cada 5 anys", "Cada 2 anys", "Mai"] },
  { q: "Quina és l'edat mínima per a obtindre el permís B?",
    o: ["18 anys", "16 anys", "17 anys", "21 anys"] },
  { q: "Quin nombre màxim de places, inclòs el conductor, pot tindre un turisme per a conduir-lo amb el permís B?",
    o: ["9", "7", "5", "12"] },
  { q: "Amb el permís B, quina massa màxima autoritzada pot tindre un remolc lleuger?",
    o: ["750 kg", "1.000 kg", "500 kg", "3.500 kg"] },
  { q: "A Espanya, amb el permís B i més de 3 anys d'antiguitat, quines motocicletes pot conduir?",
    o: ["Fins a 125 cc i 11 kW", "Qualsevol motocicleta", "Cap, necessita el permís A2", "Fins a 250 cc"] },
  { q: "Quina assegurança és obligatòria per a circular amb un turisme?",
    o: ["La de responsabilitat civil obligatòria", "La de tot risc", "La d'assistència en carretera", "Cap"] },
  { q: "Conduir sense haver obtingut mai el permís de conduir és...",
    o: ["Un delicte", "Una infracció lleu", "Una infracció greu sense més conseqüències", "Permés en trajectes curts"] },
];
